name: Lint
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
permissions:
  contents: read
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
          skip-pkg-cache: true
